# Form implementation generated from reading ui file 'e:\Projects\nhentai_grabber\src\frontend\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.linkLineEdit = QtWidgets.QLineEdit(self.tab)
        self.linkLineEdit.setObjectName("linkLineEdit")
        self.verticalLayout_3.addWidget(self.linkLineEdit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputPathLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.inputPathLineEdit.setObjectName("inputPathLineEdit")
        self.horizontalLayout.addWidget(self.inputPathLineEdit)
        self.inputPathButton = QtWidgets.QPushButton(self.tab_2)
        self.inputPathButton.setObjectName("inputPathButton")
        self.horizontalLayout.addWidget(self.inputPathButton)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputPathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.outputPathLineEdit.setObjectName("outputPathLineEdit")
        self.horizontalLayout_2.addWidget(self.outputPathLineEdit)
        self.outputPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.outputPathButton.setObjectName("outputPathButton")
        self.horizontalLayout_2.addWidget(self.outputPathButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.outputField = QtWidgets.QTextEdit(self.centralwidget)
        self.outputField.setObjectName("outputField")
        self.verticalLayout.addWidget(self.outputField)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.linkLineEdit.setPlaceholderText(_translate("MainWindow", "Ссылка на додзинси или ее номер..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ссылка"))
        self.inputPathLineEdit.setPlaceholderText(_translate("MainWindow", "Путь к текстовому файлу с ссылками на додзинси или их номерами..."))
        self.inputPathButton.setText(_translate("MainWindow", "Выбрать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Файл"))
        self.outputPathLineEdit.setPlaceholderText(_translate("MainWindow", "Путь для сохранения..."))
        self.outputPathButton.setText(_translate("MainWindow", "Выбрать"))
        self.startButton.setText(_translate("MainWindow", "Запустить"))
